"""Generate nodes/Technocore/shared/sweep-table.ts from Python's unicodedata.

Why a generated table instead of JavaScript `\\p{Cf}` regexes: the Technocore server
sweeps text with CPython's `unicodedata` (Python 3.12 -> Unicode 15.0.0 in production,
docker/Dockerfile). n8n instances run whatever Node.js they run, and each V8/ICU release
ships a different Unicode version. A signature covers the text *after* the sweep, so a
single code point categorised differently on the two sides makes the server answer 403.
Freezing the server's table removes that class of drift.

Run with the same interpreter the server uses, from the upstream checkout's venv:

    cd <technocore-chat checkout> && uv run python "<this repo>/scripts/gen-sweep-table.py" \
        > "<this repo>/nodes/Technocore/shared/sweep-table.ts"
"""

from __future__ import annotations

import sys
import unicodedata

INVISIBLE_CATEGORIES = ("Cc", "Cf", "Cs", "Co", "Zl", "Zp")


def ranges(pred) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start = None
    for cp in range(0x110000):
        hit = pred(cp)
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def fmt(rs: list[tuple[int, int]]) -> str:
    return "\n".join(f"\t[0x{a:04x}, 0x{b:04x}]," for a, b in rs)


def main() -> None:
    invisible = ranges(lambda cp: unicodedata.category(chr(cp)) in INVISIBLE_CATEGORIES)
    space = ranges(lambda cp: chr(cp).isspace())
    # major.minor only: the table depends on the Unicode database, not the patch release,
    # so CI's CPython 3.12.x must regenerate a byte-identical file.
    py = ".".join(str(p) for p in sys.version_info[:2])
    sys.stdout.write(
        "// GENERATED by scripts/gen-sweep-table.py - do not edit by hand.\n"
        f"// Source: CPython {py}, unicodedata {unicodedata.unidata_version}.\n"
        "// INVISIBLE_RANGES: code points whose category is Cc, Cf, Cs, Co, Zl or Zp\n"
        "// (the categories the Technocore server replaces with a space).\n"
        "// SPACE_RANGES: code points for which Python str.isspace() is true\n"
        "// (what str.strip() trims).\n"
        f"export const UNICODE_VERSION = '{unicodedata.unidata_version}';\n\n"
        "export const INVISIBLE_RANGES: ReadonlyArray<readonly [number, number]> = [\n"
        f"{fmt(invisible)}\n];\n\n"
        "export const SPACE_RANGES: ReadonlyArray<readonly [number, number]> = [\n"
        f"{fmt(space)}\n];\n"
    )


if __name__ == "__main__":
    main()
